=== ny83427/zorro/batch/scripts/custom_uninst/keydb.dtd
<!--
DTD for SAPinst KeyDB
version: $Id: //inst/inst_scripts/lmts_006_REL/dtds/keydb.dtd#1 $
author: Henrik Bennin (d027171), Thomas Klink (d027120)
-->

<!-- include the documentation DTD to define required docu elements -->
<!ENTITY % docudtd SYSTEM "doc.dtd">
%docudtd;

<!--
Tables consist of rows and they in turn of fields.
The name of the fields is used for assigning them to columns.
A table can belong to namespaces. If no namespace is specified,
the global namespace is assumed.
To keep external entities (XML snippets) valid one can summarize
several tables in a tableset.
-->

<!ELEMENT tables (tableset)*>
<!ATTLIST tables
  version    CDATA #IMPLIED
  changelist CDATA #IMPLIED>

<!ELEMENT tableset (table)*>
<!ATTLIST tableset
  srcid CDATA #REQUIRED>

<!ELEMENT table (doc-short?, doc-long?, columns, row*)>
<!ATTLIST table
  version    CDATA          "1.0"
  name       NMTOKEN        #REQUIRED
  namespaces NMTOKENS       #IMPLIED
  srcid      CDATA          #IMPLIED
  deprecated (true | false) #IMPLIED>

<!ELEMENT columns (column)*>

<!ELEMENT column (doc-short?, doc-long?, defaultproperties?, properties?)>
<!ATTLIST column
  name        NMTOKEN    #REQUIRED
  width       CDATA      #IMPLIED>

<!ELEMENT row (fld)*>

<!ELEMENT fld (properties?, (strval | exp))>
<!ATTLIST fld
  name NMTOKEN #REQUIRED>

<!ELEMENT strval (#PCDATA)>

<!ELEMENT exp (#PCDATA)>

<!ELEMENT properties (property+ | propertyContainer+)*>

<!ELEMENT defaultproperties (property+ | propertyContainer+)*>
<!ELEMENT property EMPTY>
<!ATTLIST property
  name  NMTOKEN #REQUIRED
  value CDATA   #IMPLIED>

<!ELEMENT propertyContainer (property+ | propertyContainer+)*>
<!ATTLIST propertyContainer
  name NMTOKEN #REQUIRED>

=== ny83427/zorro/batch/scripts/custom_inst/inifile_MSS.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="keydb.xsl" ?>
<!DOCTYPE tables SYSTEM "keydb.dtd" >
<!-- to be done  -->
<tables>
<tableset  srcid="created_by_controler">
  <table name="INIFILE_MANAGER" namespaces="INFILE_MANAGER_NS">
    <columns>
      <column name="CONFIG">
        <defaultproperties>
          <property name ="SAPINST_INSTANCE_ID_GENERATION" value ="SUBCOMPONENT_ID" />
        </defaultproperties>
      </column>
    </columns>
  </table>
  <table name="-NW_Java_OneHost-ind-ind-ind-ind-0-0-NW_First_Steps-ind-ind-ind-ind-firstSteps-0-Preinstall-ind-ind-ind-ind-Preinstall-0" namespaces="INIFILE_PARAMETER">
    <columns>
      <column name="installationMode">
        <defaultproperties>
          <property name ="SAPINST_ORIGINAL_TABLE_NAME" value ="t_pre" />
        </defaultproperties>
      </column>
    </columns>
    <row>
      <fld name="installationMode">
        <properties>
          <property name ="doc-long" value ="standard or custom " />
        </properties>
        <strval><![CDATA[standard]]>
        </strval>
      </fld>
    </row>
  </table>
  <table name="ParameterTable-NW_Java_OneHost-ind-ind-ind-ind-0-0-SelectOptionalUnits-ind-ind-ind-ind-optUnits-0_t_software_features" namespaces="INIFILE_PARAMETER">
    <columns>
      <column name="DEPENDS_ON_EXP">
        <defaultproperties>
          <property name ="TABLE_DOC_SHORT_LONG" value ="
Set the field IS_ACTIVE_CHOICE to true for each usage types you want to install." />
        </defaultproperties>
      </column>
      <column name="IS_ACTIVE">
      </column>
      <column name="IS_ACTIVE_CHOICE">
      </column>
      <column name="IS_POSSIBLE">
      </column>
      <column name="LONG_NAME">
      </column>
      <column name="NAME">
      </column>
      <column name="PRODUCT_CODE">
      </column>
      <column name="SHORT_NAME">
      </column>
      <column name="VENDOR">
      </column>
    </columns>
    <row>
      <fld name="DEPENDS_ON_EXP">
        <properties>
          <property name ="TABLE_DOC_SHORT_LONG" value ="
Set the field IS_ACTIVE_CHOICE to true for each usage types you want to install." />
        </properties>
        <strval><![CDATA[]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE_CHOICE">
        <strval><![CDATA[]]>
        </strval>
      </fld>
      <fld name="IS_POSSIBLE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="LONG_NAME">
        <strval><![CDATA[Application Server ABAP]]>
        </strval>
      </fld>
      <fld name="NAME">
        <strval><![CDATA[AAS]]>
        </strval>
      </fld>
      <fld name="PRODUCT_CODE">
        <strval><![CDATA[NetWeaver]]>
        </strval>
      </fld>
      <fld name="SHORT_NAME">
        <strval><![CDATA[Application Server ABAP]]>
        </strval>
      </fld>
      <fld name="VENDOR">
        <strval><![CDATA[sap.com]]>
        </strval>
      </fld>
    </row>
    <row>
      <fld name="DEPENDS_ON_EXP">
        <properties>
          <property name ="TABLE_DOC_SHORT_LONG" value ="
Set the field IS_ACTIVE_CHOICE to true for each usage types you want to install." />
        </properties>
        <strval><![CDATA[ADOBE, BASIC, NW-MODEL]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE_CHOICE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="IS_POSSIBLE">
        <strval><![CDATA[true]]>
        </strval>
      </fld>
      <fld name="LONG_NAME">
        <strval><![CDATA[ALV Export Services]]>
        </strval>
      </fld>
      <fld name="NAME">
        <strval><![CDATA[ALV-EXPORT]]>
        </strval>
      </fld>
      <fld name="PRODUCT_CODE">
        <strval><![CDATA[NetWeaver]]>
        </strval>
      </fld>
      <fld name="SHORT_NAME">
        <strval><![CDATA[ALV Export Services]]>
        </strval>
      </fld>
      <fld name="VENDOR">
        <strval><![CDATA[sap.com]]>
        </strval>
      </fld>
    </row>
    <row>
      <fld name="DEPENDS_ON_EXP">
        <properties>
          <property name ="TABLE_DOC_SHORT_LONG" value ="
Set the field IS_ACTIVE_CHOICE to true for each usage types you want to install." />
        </properties>
        <strval><![CDATA[NW-MODEL]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE_CHOICE">
        <strval><![CDATA[true]]>
        </strval>
      </fld>
      <fld name="IS_POSSIBLE">
        <strval><![CDATA[true]]>
        </strval>
      </fld>
      <fld name="LONG_NAME">
        <strval><![CDATA[Application Server Java]]>
        </strval>
      </fld>
      <fld name="NAME">
        <strval><![CDATA[BASIC]]>
        </strval>
      </fld>
      <fld name="PRODUCT_CODE">
        <strval><![CDATA[NetWeaver]]>
        </strval>
      </fld>
      <fld name="SHORT_NAME">
        <strval><![CDATA[Application Server Java]]>
        </strval>
      </fld>
      <fld name="VENDOR">
        <strval><![CDATA[sap.com]]>
        </strval>
      </fld>
    </row>
    <row>
      <fld name="DEPENDS_ON_EXP">
        <properties>
          <property name ="TABLE_DOC_SHORT_LONG" value ="
Set the field IS_ACTIVE_CHOICE to true for each usage types you want to install." />
        </properties>
        <strval><![CDATA[BASIC, NW-MODEL]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE_CHOICE">
        <strval><![CDATA[]]>
        </strval>
      </fld>
      <fld name="IS_POSSIBLE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="LONG_NAME">
        <strval><![CDATA[Demo Applications]]>
        </strval>
      </fld>
      <fld name="NAME">
        <strval><![CDATA[BASIC-RA]]>
        </strval>
      </fld>
      <fld name="PRODUCT_CODE">
        <strval><![CDATA[NetWeaver]]>
        </strval>
      </fld>
      <fld name="SHORT_NAME">
        <strval><![CDATA[Demo Applications]]>
        </strval>
      </fld>
      <fld name="VENDOR">
        <strval><![CDATA[sap.com]]>
        </strval>
      </fld>
    </row>
    <row>
      <fld name="DEPENDS_ON_EXP">
        <properties>
          <property name ="TABLE_DOC_SHORT_LONG" value ="
Set the field IS_ACTIVE_CHOICE to true for each usage types you want to install." />
        </properties>
        <strval><![CDATA[BASIC, NW-MODEL]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE_CHOICE">
        <strval><![CDATA[]]>
        </strval>
      </fld>
      <fld name="IS_POSSIBLE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="LONG_NAME">
        <strval><![CDATA[NWDS Update Site]]>
        </strval>
      </fld>
      <fld name="NAME">
        <strval><![CDATA[IDE-Update-Site]]>
        </strval>
      </fld>
      <fld name="PRODUCT_CODE">
        <strval><![CDATA[NetWeaver]]>
        </strval>
      </fld>
      <fld name="SHORT_NAME">
        <strval><![CDATA[NWDS Update Site]]>
        </strval>
      </fld>
      <fld name="VENDOR">
        <strval><![CDATA[sap.com]]>
        </strval>
      </fld>
    </row>
    <row>
      <fld name="DEPENDS_ON_EXP">
        <properties>
          <property name ="TABLE_DOC_SHORT_LONG" value ="
Set the field IS_ACTIVE_CHOICE to true for each usage types you want to install." />
        </properties>
        <strval><![CDATA[]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE_CHOICE">
        <strval><![CDATA[true]]>
        </strval>
      </fld>
      <fld name="IS_POSSIBLE">
        <strval><![CDATA[true]]>
        </strval>
      </fld>
      <fld name="LONG_NAME">
        <strval><![CDATA[NW Product Description]]>
        </strval>
      </fld>
      <fld name="NAME">
        <strval><![CDATA[NW-MODEL]]>
        </strval>
      </fld>
      <fld name="PRODUCT_CODE">
        <strval><![CDATA[NetWeaver]]>
        </strval>
      </fld>
      <fld name="SHORT_NAME">
        <strval><![CDATA[NW-MODEL]]>
        </strval>
      </fld>
      <fld name="VENDOR">
        <strval><![CDATA[sap.com]]>
        </strval>
      </fld>
    </row>
    <row>
      <fld name="DEPENDS_ON_EXP">
        <properties>
          <property name ="TABLE_DOC_SHORT_LONG" value ="
Set the field IS_ACTIVE_CHOICE to true for each usage types you want to install." />
        </properties>
        <strval><![CDATA[]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="IS_ACTIVE_CHOICE">
        <strval><![CDATA[]]>
        </strval>
      </fld>
      <fld name="IS_POSSIBLE">
        <strval><![CDATA[false]]>
        </strval>
      </fld>
      <fld name="LONG_NAME">
        <strval><![CDATA[PI Adapter Engine Standalone]]>
        </strval>
      </fld>
      <fld name="NAME">
        <strval><![CDATA[PI-AE-SE]]>
        </strval>
      </fld>
      <fld name="PRODUCT_CODE">
        <strval><![CDATA[NetWeaver]]>
        </strval>
      </fld>
      <fld name="SHORT_NAME">
        <strval><![CDATA[PI Adapter Engine Standalone]]>
        </strval>
      </fld>
      <fld name="VENDOR">
        <strval><![CDATA[sap.com]]>
        </strval>
      </fld>
    </row>
    <row>
      <fld name="DEPENDS_ON_EXP">
        <properties>
          <property name ="TABLE_DOC_SHORT_LONG" value ="
Set the field IS_ACTIVE_CHOICE to true for each usage types you want to install." />
        </properties>
        <strval><![CDATA[ESR, PI-AF]]>
        </strval>
      </fld>
